.PHONY:NotHotCompress
NotHotCompress:NotHotCompress.cpp
	g++ -std=c++11 $^ -o $@ -L/usr/lib64/mysql -lmysqlclient -lpthread -lboost_filesystem -lboost_system -lz
FileNameManager:FileNameManager.cpp
	g++ -std=c++11 $^ -o $@ -L/usr/lib64/mysql -lmysqlclient -lpthread
